name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: test
    env:
        image: rundcode/jenkins-sosialmedia
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
          
    - name: Build Docker Image
      run: docker build -t $image:$GITHUB_SHA .

    - name: Push Docker Image
      run: docker push $image:$GITHUB_SHA
